#!/usr/bin/env python3
"""Regenerate each unit's header.c parameter table from its effect.h.

effect.h is the single source of truth:
  * The param enum — `enum { SIZE = 0U, TONE, DEPTH, MODE, NUM_PARAMS };` —
    gives the names of params 0..3 (X, Y, DEPTH, MODE) shown on the NTS-3.
  * The mode enum + the Params default (`uint32_t mode = M_MED;`) give the
    MODE count and its default. Mode *labels* stay in getParameterStrValue().
  * Param 4 is always DRIVE.
  * Optional directives in comments:
      // @map x <min> <max> <default>      pad X range/default   (default 0 1023 256)
      // @map y <min> <max> <default>      pad Y range/default   (default 0 1023 512)
      // @param <5..7> <NAME> <min> <max> <default>   extra knob (edit menu)
      // @drive <default>                  DRIVE default (0..1023, default 250)
      // @manual-header                    leave this unit's header.c alone

Usage: scripts/sync_params.py [unit ...]     (no args = every unit)
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
UNITS = ROOT / "units"


def parse(effect: str):
    code = re.sub(r"//[^\n]*", "", effect)  # names only — comments may contain commas
    enums = re.findall(r"enum\s*\{([^}]*)\}", code)
    params = modes = None
    for body in enums:
        names = [n.split("=")[0].strip() for n in body.split(",") if n.strip()]
        if "NUM_PARAMS" in names and params is None:
            params = [n for n in names if n != "NUM_PARAMS"]
        elif names and names[-1].startswith("NUM_") and modes is None and params is not None:
            modes = names[:-1]
    if not params or len(params) < 4:
        raise ValueError("no `enum { ..., NUM_PARAMS }` with 4 entries")
    if not modes:
        raise ValueError("no mode enum after the param enum")
    # default mode: `<field> = M_XXX` inside struct Params
    m = re.search(r"struct Params\s*\{([^}]*)\}", code, re.S)
    default_mode = 0
    if m:
        for cand in modes:
            if re.search(r"=\s*" + re.escape(cand) + r"\b", m.group(1)):
                default_mode = modes.index(cand)
    maps = {"x": (0, 1023, 256), "y": (0, 1023, 512)}
    for axis, lo, hi, df in re.findall(r"(?://|\*)\s*@map\s+([xy])\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)", effect):
        maps[axis] = (int(lo), int(hi), int(df))
    extra = {}
    for idx, name, lo, hi, df in re.findall(r"(?://|\*)\s*@param\s+([5-7])\s+(\S+)\s+(-?\d+)\s+(-?\d+)\s+(-?\d+)", effect):
        extra[int(idx)] = (name[:21], int(lo), int(hi), int(df))
    d = re.search(r"(?://|\*)\s*@drive\s+(\d+)", effect)
    drive = int(d.group(1)) if d else 250
    return params, len(modes), default_mode, maps, extra, drive


def render(params, nmodes, dmode, maps, extra, drive):
    P, M = [], []
    x, y = maps["x"], maps["y"]
    P.append(f'{{0, 1023, 0, {x[2]}, k_unit_param_type_none, 0, 0, 0, {{"{params[0][:21]}"}}}}')
    M.append(f"{{k_genericfx_param_assign_x, k_genericfx_curve_linear, k_genericfx_curve_unipolar, {x[0]}, {x[1]}, {x[2]}}}")
    P.append(f'{{0, 1023, 0, {y[2]}, k_unit_param_type_none, 0, 0, 0, {{"{params[1][:21]}"}}}}')
    M.append(f"{{k_genericfx_param_assign_y, k_genericfx_curve_linear, k_genericfx_curve_unipolar, {y[0]}, {y[1]}, {y[2]}}}")
    P.append('{-1000, 1000, 0, 0, k_unit_param_type_drywet, 1, 1, 0, {"DEPTH"}}')
    M.append("{k_genericfx_param_assign_depth, k_genericfx_curve_exp, k_genericfx_curve_bipolar, -1000, 1000, 0}")
    P.append(f'{{0, {nmodes - 1}, 0, {dmode}, k_unit_param_type_strings, 0, 0, 0, {{"{params[3][:21]}"}}}}')
    M.append(f"{{k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, {nmodes - 1}, {dmode}}}")
    P.append(f'{{0, 1023, 0, {drive}, k_unit_param_type_none, 0, 0, 0, {{"DRIVE"}}}}')
    M.append(f"{{k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 1023, {drive}}}")
    n = 5
    for i in (5, 6, 7):
        if i in extra:
            name, lo, hi, df = extra[i]
            P.append(f'{{{lo}, {hi}, 0, {df}, k_unit_param_type_none, 0, 0, 0, {{"{name}"}}}}')
            M.append(f"{{k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, {lo}, {hi}, {df}}}")
            n = i + 1
        else:
            P.append('{0, 0, 0, 0, k_unit_param_type_none, 0, 0, 0, {""}}')
            M.append("{k_genericfx_param_assign_none, k_genericfx_curve_linear, k_genericfx_curve_unipolar, 0, 0, 0}")
    if any(i in extra for i in (5, 6, 7)) and any(i not in extra for i in range(5, n)):
        raise ValueError("@param slots must be contiguous from 5")
    params_block = (".params = {\n      // Generated by scripts/sync_params.py from effect.h — edit there, not here.\n"
                    "      // Format: min, max, center (unused), default, type, frac. bits, frac. mode, <reserved>, name\n      "
                    + ",\n      ".join(P) + "},\n  },")
    maps_block = (".default_mappings = {\n    // Generated by scripts/sync_params.py. Format: assign, curve, curve polarity, min, max, default\n    "
                  + ",\n    ".join(M) + "\n  }")
    return n, params_block, maps_block


def sync(unit: pathlib.Path):
    effect = (unit / "effect.h").read_text()
    if "@manual-header" in effect:
        return "manual"
    header_path = unit / "header.c"
    header = header_path.read_text()
    n, pb, mb = render(*parse(effect))
    header = re.sub(r"\.num_params = \d+,", f".num_params = {n},", header)
    header = re.sub(r"\.params = \{.*?\n  \},", lambda _: pb, header, count=1, flags=re.S)
    header = re.sub(r"\.default_mappings = \{.*?\n  \}", lambda _: mb, header, count=1, flags=re.S)
    header_path.write_text(header)


def main():
    names = sys.argv[1:] or sorted(p.name for p in UNITS.iterdir() if (p / "effect.h").exists())
    bad = skipped = 0
    for name in names:
        try:
            if sync(UNITS / name) == "manual":
                skipped += 1
        except Exception as e:  # report and keep going
            bad += 1
            print(f"{name}: {e}")
    print(f"synced params for {len(names) - bad - skipped} unit(s)"
          + (f", {skipped} manual" if skipped else "") + (f", {bad} failed" if bad else ""))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
